config/routes.rb
Rails.application.routes.draw do

  get 'yu_blogs/genre/:id', to: 'yu_blogs#genre'
  get 'yu_blogs/genre/:id/:page', to: 'yu_blogs#genre'

  get 'yu_blogs/show/:id', to: 'yu_blogs#show'

  get 'blogposts', to: 'blogposts#index'

  resources :blogposts, only:[:new, :create, :edit, :update, :destroy]

  get 'blogposts/:id', to: 'blogposts#edit'

  
  get 'blogposts/destroy/:id', to: 'blogposts#destroy'
  post 'blogposts/destroy', to: 'blogposts#destroy'
  post 'blogposts/destroy/:id', to: 'blogposts#destroy'

  get 'bloggenres', to: 'bloggenres#index'

  resources :bloggenres, only:[:new, :create, :edit, :update]

  get 'bloggenres/:id', to: 'bloggenres#edit'
  
  devise_for :accounts
  root 'yu_blogs#index'

  resources :yu_blogs do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
    has_many :blogpost

    validates :name, presence: {message:'は必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
    belongs_to :bloggenre
    has_one_attached :image
    has_rich_text :content

    validates :title, :content, :image, presence: {message:'は必須項目です。'}

    validate :image_content_type, if: :was_attached?

    def image_content_type
        extension = ['image/png', 'image/jpg', 'image/jpeg']
        errors.add(:image, "の拡張子が間違っています") unless image.content_type.in?(extension)
    end

    def was_attached?
        self.image.attached?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bloggenres_controller.rb
class BloggenresController < ApplicationController
    layout 'blog'
    before_action :authenticate_account!
    def index
        @data = Bloggenre.all
    end

    def new
        @bloggenre = Bloggenre.new
    end

    def create
        @bloggenre = Bloggenre.new
        if request.post? then
            @bloggenre = Bloggenre.create bloggenre_params
            redirect_to '/bloggenres'
        end
    end

    def edit
        @bloggenre = Bloggenre.find params[:id]
    end

    def update
        @bloggenre = Bloggenre.find params[:id]
        if request.patch? then
            @bloggenre.update bloggenre_params
            redirect_to '/bloggenres'
        end
    end
    private
    def bloggenre_params
        params.require(:bloggenre).permit(:name)
    end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
    layout 'blog'
    before_action :authenticate_account!
    def index
        @data = Blogpost.all.order('created_at desc')
    end

    def new
        @blogpost = Blogpost.new
        @genre = Bloggenre.all
    end

    def create
        @blogpost = Blogpost.new
        if request.post? then
            @blogpost = Blogpost.create blogposts_params
            redirect_to '/blogposts'
        end
    end

    def edit
        @blogpost = Blogpost.find params[:id]
        @genre = Bloggenre.all
    end

    def update
        @blogpost = Blogpost.find(params[:id])
        @genre = Bloggenre.all
        if request.patch? then
            @blogpost.update blogposts_params
            redirect_to '/blogposts'
        end
    end

    def destroy
        @blogpost = Blogpost.find(params[:id])
        if request.post? then
            @blogpost.destroy
            redirect_to '/blogposts'
        end
    end
    
    private
    def blogposts_params
        params.require(:blogpost).permit(:title, :read, :content, :bloggenre_id, :image)
    end
end

app/controllers/yu_blogs_controller.rb
class YuBlogsController < ApplicationController
    before_action :search_params
    before_action :genre_get, only: [:index, :show, :search]
    layout 'blogs'

    def index
        @data = Blogpost.order('created_at desc').page params[:page]
    end

    def genre
        @genre = Bloggenre.find params[:id]
        @data = Blogpost.where('bloggenre_id = ?',params[:id]).order('created_at desc').page params[:page]
        @results = @q.result.page params[:page]
    end

    def show
        @blogpost = Blogpost.find(params[:id])
        @results = @q.result.page params[:page]
    end

    def search 
        @results = @q.result.page params[:page]
    end

    private

    def search_params
        @q = Blogpost.order('created_at desc').ransack(params[:q])
    end

    def genre_get
        @genre = Bloggenre.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggenres_helper.rb
module BloggenresHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/yu_blogs_helper.rb
module YuBlogsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bloggenres/_form.html.erb
<%= form_with model: @bloggenre, local: true do |f| %>
    <div class = "form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, {class:"form-control"} %>
    </div>
    <p><%= f.submit "作成" %></p>
<% end %>

app/views/bloggenres/create.html.erb
<h1>Bloggenres#create</h1>
<p>Find me in app/views/bloggenres/create.html.erb</p>

app/views/bloggenres/edit.html.erb
<h1 class = "display-4 text-primary">ジャンルの編集</h1>
<% if @bloggenre.errors.any? %>
    <ul>
        <% @bloggenre.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>
<%= render partial: 'form' %>

app/views/bloggenres/index.html.erb
<h1 class = "display-4 text-primary">ブログのジャンル</h1>
<p>ジャンル一覧</p>
<table class = "table">
    <tr>
        <th>ID</th><th>Name</th><th></th>
    </tr>
    <% @data.each do |obj| %>
    <tr>
        <td><%= obj.id %></td>
        <td><%= obj.name %></td>
        <td><a href = "/bloggenres/<%= obj.id %>">Edit</a><td>
    </tr>
    <% end %>
</table>
<p><a href = "/bloggenres/new">ジャンル追加</a></p>
<p><a href = "/blogposts">ブログ投稿ページへ</a></p>
<div><%= link_to 'サインアウト', destroy_account_session_path, method: :delete %></div>

app/views/bloggenres/new.html.erb
<h1 class = "display-4 text-primary">ジャンルの新規作成</h1>
<% if @bloggenre.errors.any? %>
    <ul>
        <% @bloggenre.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>
<%= render partial: 'form' %>

app/views/bloggenres/update.html.erb
<h1>Bloggenres#update</h1>
<p>Find me in app/views/bloggenres/update.html.erb</p>

app/views/blogposts/_form.html.erb
<%= form_with model: @blogpost, local: true do |f| %>
    <div class = "form-group">
        <%= f.label :title, 'Ttile' %>
        <%= f.text_field :title, {class:"form-control"} %>
    </div>
    <div class = "form-group">
        <%= f.label :read, 'Read' %>
        <%= f.text_field :read, {class:"form-control"} %>
    </div>
    <div class = "form-group">
        <%= f.label :image %>
        <%= f.file_field :image, accept: "image/png, image/jpeg, image/gif" %>
    </div>
    <div class = "form-group">
        <%= f.label :content, 'Content' %>
        <%= f.rich_text_area :content %>
    </div>
    <div class = "form-group">
        <%= f.label :bloggenre_id %>
        <%= f.collection_select :bloggenre_id, @genre, :id, :name , {}, {class: "form-control"}%>
    </div>
    <p><%= f.submit "作成" %></p>
<% end %>

app/views/blogposts/create.html.erb
<h1>Blogposts#create</h1>
<p>Find me in app/views/blogposts/create.html.erb</p>

app/views/blogposts/destroy.html.erb
<h1 class = "display-4 text-primary">ブログ削除</h1>
<p>以下を削除してもいいですか？</p>
<table class = "table">
    <tr><th>Id</th>
        <td><%= @blogpost.id %></td>
    </tr>
    <tr><th>Title</th>
        <td><%= @blogpost.title %></td>
    </tr>
    <tr><th>Read</th>
        <td><%= @blogpost.read %></td>
    </tr>
    <tr><th>Content</th>
        <td><%= @blogpost.content %></td>
    </tr>
</table>
<%= form_tag controller: "blogposts", action: "destroy" do %>
    <%= hidden_field_tag "id", {value: @blogpost.id} %>
    <%= submit_tag "削除" %>
<% end %>

app/views/blogposts/edit.html.erb
<h1 class = "text-primary display-4">ブログの編集</h1>
<% if @blogpost.errors.any? %>
    <ul>
        <% @blogpost.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>
<%= render partial: 'form' %>

app/views/blogposts/index.html.erb
<h1 class = "display-4 text-primary">Yu-Blog</h1>
<p>*投稿記事の一覧</p>
<table class = "table">
    <tr>
        <th>タイトル</th><th>見出し</th><th>ジャンル</th><th colspan = "2"></th>
    </tr>
    <% @data.each do |obj| %>
        <tr>
            <td><%= obj.id %></td>
            <td><%= obj.title %></td>
            <td><%= obj.read %></td>
            <td><%= obj.bloggenre.name %></td>
            <td><a href = "/blogposts/<%= obj.id %>">編集</a></td>
            <td><a href = "/blogposts/destroy/<%= obj.id %>">削除</a></td>
        </tr>
    <% end %>
</table>
<p><a href = "/blogposts/new">新規作成</a></p>
<p><a href = "/bloggenres">ジャンル一覧ページへ</a></p>
<p><a href = "/">ブログ一覧へ</a></p>
<div><%= link_to 'サインアウト', destroy_account_session_path, method: :delete %></div>

app/views/blogposts/new.html.erb
<h1 class = "text-primary display-4">ブログの新規作成</h1>
    <% if @blogpost.errors.any? %>
        <ul>
            <% @blogpost.errors.full_messages.each do |err| %>
                <li><%= err %></li>
            <% end %>
        </ul>
    <% end %>
<%= render partial: 'form' %>

app/views/blogposts/update.html.erb
<h1>Blogposts#update</h1>
<p>Find me in app/views/blogposts/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>App</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>MyBlog</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <%= stylesheet_link_tag 'blog', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= stylesheet_link_tag 'actiontext', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= yield %>
        <div class = "mt-5 text-center small text-scondary border-top border-scondary">2020 YU-Blog.</div>
    </body>
</html>

app/views/layouts/blogs.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>MyBlog</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= stylesheet_link_tag 'actiontext', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://kit.fontawesome.com/424ac5601c.js" crossorigin="anonymous"></script>
    </head>

    <body class = "container">
        <header class = "header">
            <h1 class = "display-4 mb-4"><a href = "/">YU-BLOG</a></h1>
            <p class = "contact" id = "contact">CONTACT</p>
            <nav class = "nav">
                <ul class = "nav-ul">
                    <li class = "nav-list"><a href = "https://twitter.com/yu63001712"><i class="fab fa-twitter"></i></a></li>
                    <li class = "nav-list"><a href = "https://github.com/yu-corder"><i class="fab fa-github"></i></a></li>
                    <li class = "nav-list nav-close" id = "nav-close">Close</li>
                </ul>
            </nav>
        </header>
        <hr>
        <div class = "box top-box">
            <main class = "main" id = "main">
                <div class = "top hide" id = "top">
                    <h2 class = "genre-show"><i class="fas fa-star"></i>ジャンル別<i class="fas fa-star"></i></h2>
                    <ul class = "top-ul">
                        <% Bloggenre.all.each do |genre| %>
                            <li class = "genres top-list"><a href = "/yu_blogs/genre/<%= genre.id %>"><%= genre.name %></a></li>
                        <% end %>
                    </ul>
                    <%= search_form_for(@q, url:search_yu_blogs_path) do |f| %>
                        <%= f.search_field :read_cont %>
                        <br>
                        <%= f.submit %>
                    <% end %>
                </div>
            <%= yield %>
            </main>
            <aside class = "side" id = "side">
                <p class = "logo-box"><%= image_tag 'yublogman.png', class: 'bloglogo' %></p>
                <h2 class = "profile"><i class="fas fa-star"></i>管理人の紹介<i class="fas fa-star"></i></h2>
                <p class = "profile-text">
                    管理人のユーです。！<br>
                    ただいま色々勉強中です。<br>
                    よろしくお願いします。
                </p>
                <h2 class = "genre-show"><i class="fas fa-star"></i>ジャンル別<i class="fas fa-star"></i></h2>
                <% Bloggenre.all.each do |genre| %>
                    <p class = "genres"><a href = "/yu_blogs/genre/<%= genre.id %>"><%= genre.name %></a></p>
                <% end %>
                <%= search_form_for(@q, url:search_yu_blogs_path) do |f| %>
                    <%= f.search_field :read_cont %>
                    <br>
                    <%= f.submit %>
                <% end %>
            </aside>
        </div>
        <footer class = "mt-5 text-center small text-scondary border-top border-scondary">2020 YU-Blog.</footer>
    </body>
</html>

app/views/yu_blogs/genre.html.erb
<h2 class = "h3 mb-4 genre-page"><%= @genre.name %></h2>
<article class = "d-flex flex-fill justify-content-around flex-wrap ">
    <% @data.each do |obj| %>
        <section class = "blog-box col-md-5 ">
            <a class = "blog-link" href = "/yu_blogs/show/<%= obj.id %>">
            <p><%= image_tag obj.image.variant(resize_to_fill:[800,600]).processed, class:'img-fluid img-thumbnail' if obj.image.attached? %></p>
            <span class = "time"><%= obj.created_at.to_s(:datetime_jp) %></span>
            <span class = "genre-name">- <%= @genre.name %> -</span>
            <h3 class = "blog-title"><%= obj.title %></h3>
            <p><%= obj.read %></p>
            </a>
        </section>
    <% end %>
</article>
<div class = "navigate mt-4">
    <div><%= paginate @data %></div>
</div>

app/views/yu_blogs/index.html.erb
<article class = "d-flex flex-fill justify-content-around flex-wrap ">
    <% @data.each do |obj| %>
        <section class = "blog-box col-md-5 ">
            <a class = "blog-link" href = "/yu_blogs/show/<%= obj.id %>">
            <p><%= image_tag obj.image.variant(resize_to_fill:[800,600]).processed, class:'img-fluid img-thumbnail' if obj.image.attached? %></p>
            <span class = "time"><%= obj.created_at.to_s(:datetime_jp) %></span>
            <span class = "genre-name">- <%= @genre[obj.bloggenre_id - 1].name %> -</sapn>
            <h3 class = "blog-title"><%= obj.title %></h3>
            <p><%= obj.read %></p>
            </a>
        </section>
    <% end %>
</article>
<div class = "navigate">
    <div class = "paginate"><%= paginate @data %></div>
</div>

app/views/yu_blogs/search.html.erb
<h1 class = "h3 search-result">検索結果です</h1>
<p class = "hit-text"><%= @results.total_count %>件ヒット</p>
<article class = "d-flex flex-fill justify-content-around flex-wrap ">
    <% if @results.present? %>
        <% @results.each do |result| %>
            <section class = "blog-box col-md-5 ">
            <a class = "blog-link" href = "/yu_blogs/show/<%= result.id %>">
            <p><%= image_tag result.image.variant(resize_to_fill:[800,600]).processed, class:'img-fluid img-thumbnail' if result.image.attached? %></p>
            <span class = "time"><%= result.created_at.to_s(:datetime_jp) %></span>
            <span class = "genre-name">- <%= @genre[result.bloggenre_id - 1].name %> -</sapn>
            <h3 class = "blog-title"><%= result.title %></h3>
            <p><%= result.read %></p>
            </a>
            </section>
        <% end %>
    <% else %>
        <p class = "hit-text">ヒット無し</p>
    <% end %>
</article>
<div class = "navigate">
    <div class = "paginate"><%= paginate @results %></div>
</div>

app/views/yu_blogs/show.html.erb
<article>
    <section>
        <h2 class = "mb-5 show-title"><%= @blogpost.title %></h2>
        <div class = "show-box">
            <p class ="show-time"><%= '[' + @blogpost.created_at.to_s(:datetime_jp) + ']' %></p>
            <span class = "show-genre-link"><a href = "/yu_blogs/genre/<%= @blogpost.bloggenre_id %>">- <%= @genre[@blogpost.bloggenre_id - 1].name %> -</a></sapn>
        </div>
        <p class = "blog-content"><%= @blogpost.content %></p>
        <p class = "home"><a href = "/">ホームへ戻る</a></p>
    </section>
</article>